name: release-helm

on:
  release:
    types: [published]

jobs:
  helmrelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package and publish Helm chart
        run: |
          helm package deploy/edge-receiver --version ${{ github.event.release.tag_name }}
          helm chart push edge-receiver-${{ github.event.release.tag_name }}.tgz ghcr.io/${{ github.repository }}/edge-receiver-chart:${{ github.event.release.tag_name }}
